---

 - name: Add Fish PPA 
   become: yes
   apt_repository:
     repo: ppa:fish-shell/release-3  
   tags:
    - install
    - fish

 - name: Install Fish
   become: yes
   package:
     name: fish
     state: latest
   tags:
   - fish
