#!/bin/bash

if [ ! -f /etc/ansible/install ]; then 
        if [ "$(lsb_release -is)" == Ubuntu ]; then
                sudo apt update
                sudo apt install git ansible
                sudo rm -dr /etc/ansible/
                cd ~/.ansible/
                sudo git clone https://github.com/aksratamo/ansible.git
                ansible-playbook ~/.ansible/ansible/site.yml --check
        fi
fi


