---
 - hosts: basic

   roles:  
   - basic_apps
   - firefox
 


 - hosts: advanced
   roles:
    - keepassxc
    - fish
    

   tasks: 
   - name: PPA roles
     include_role:
       name: advanced_ppa
    