---
 - hosts: basic

   roles:
   - helloworld
   - basic_apps
   - firefox
 


 - hosts: advanced
   roles:
    - keepassxc
    - fish
    

   tasks: 
   - name: PPA roles
     include_role:
       name: advanced_ppa
     when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
