---
- hosts: basic

  roles:
  - helloworld
  - basic_apps

  tasks: 
  - name: PPA roles
    include_role:
      name: advanced_ppa
    when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
