---
 - name: KeepassXC PPA
   become: yes
   apt_repository:
     repo: ppa:phoerious/keepassxc
   tags:
    - install
    - keepassxc
    
 - name: Install KeepassXC 
   become: yes
   package: 
     name: keepassxc
     state: latest
   tags:
    - install
    - keepassxc
